### ISSUE TITLE
Straightforward option to preserve workdir, or files from it?

### ISSUE THREAD

**Issue by hangtwenty** [ajk8/hatchery#10]
I'd like to preserve at least my `coverage.xml` if not other files, from `.hatchery.work` after `hatchery test` is done. Much like Gradle's `build` directory sticks around. Would this violate design constraints you want to preserve? In my mind this would be another option that could go in `hatchery.yml`

**Comment by hangtwenty** [comment]
See https://github.com/ajk8/workdir-python/issues/3

**Comment by ajk8** [comment]
@hangtwenty can you be more specific about the workflow you're looking to promote here? What are the sequence of steps, starting from a clean workspace, that you would like to execute?

**Comment by hangtwenty** [comment]
When I run my tests (via `tox` and/or `py.test`), code coverage is calculated. This is output by default to `coverage.xml` in the directory the test are run in. I _could_ bend my test configuration to do something like save that in the directory above, but that seems dirty to me... I don't want my test config to know about `hatchery` etc. OK so I have `coverage.xml` either in base directory if running natively, or in `.hatchery.work` if I'm running my tests through `hatchery test`. In the latter case... `coverage.xml` is deleted when `.hatchery.work` is done. I really don't have any desire for `.hatchery.work` to be deleted automatically anyways, so I'd rather just leave the files around, much like Gradle leaves its `build` directory around. (And relies on you, the user, to know if that dir needs deleting or `clean`ing.) (Indeed I was just dealing with some code coverage stuff w/ Gradle and it was straightforward to use the coverage file, from in the `build` directory, after Gradle was all done. So this is pretty much just borrowing from that experience.)

If you want to make this feature more generic by specifying specific files to keep around or remove, that's no issue to my user story, but it's not a feature I'm after. All I want is this:

```
---
pypi_repository: https://foobar.com
readme_to_rst: False
workdir_cleanup: False
test_command:
    - tox
```

Or alternatively, we could make it so you specify certain hatchery subcommands that don't get cleanup.

```
---
pypi_repository: https://foobar.com
readme_to_rst: False
preserve_workdir_after:
    - test
test_command:
    - tox
```

**Comment by hangtwenty** [comment]
Doh. The directory is not deleted by default. This is my dumb fault. I was checking with `ls` and I had forgotten that `ls` (or maybe, my shell?) will ignore hidden directories... sooo

```
$ ls **/coverage.xml
```

didn't discover and I just assumed all of `.hatchery.work` was gone or something, and really I should have tried a second time...

```
$ find . -name 'coverage.xml'
./.hatchery.work/coverage.xml
```

So... dumb mistake on my part
