### ISSUE TITLE
Document test directory naming specifications

### ISSUE THREAD

**Issue by tyrostone** [ajk8/hatchery#4]
Hatchery follows naming-conventions for the top-level test directory. This directory must be named `tests`, otherwise, hatchery will error out when running `hatchery test`.

```$ hatchery test -s
ERROR:hatchery.main:detected too many top-level packages...something is amiss:```

Ideally, this would be documented and possibly have improved the error messaging.

**Comment by ajk8** [comment]
@tyrostone please close this ticket if you are satisfied with the readme changes.

**Comment by tyrostone** [comment]
Yep looks good!
