### ISSUE TITLE
Document example of using hatchery with common py.test + tox toolchain

### ISSUE THREAD

**Issue by hangtwenty** [ajk8/hatchery#7]
I think this is a valid example:

```
$ cat .hatchery.yml
---
pypi_repository: foobarbaz

test_command:
    - tox
```

as it seemed to just work. this is in a project with a `tox.ini` (and inside that `tox.ini` is a `[pytest]` block, as is common practice).

I am happy to help with contributing such an example but LMK what you think and how you'd like it to look (something in the README, a gist.github.com full example that we link to, etc.)

**Comment by ajk8** [comment]
@hangtwenty please close this ticket if you are satisfied with the readme changes.
